### ISSUE TITLE
Issue with /ss buy

### ISSUE THREAD

**Issue by Augustin37** [Hbecher/RegionSelfService#1]
Hello! I have this issue when I do **/ss buy** in front of a sign. In the chat it tells me
``` {r}
You re not allowed to execute command /ss buy
```
And I get this error : 
``` java
[20:24:29 ERROR]: Could not pass event PlayerInteractEvent to RegionSelfService v2.0.2-HB-b7
org.bukkit.event.EventException
>       at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.9.2.jar:git-Paper-717]
>       at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.9.2.jar:git-Paper-717]
>       at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.9.2.jar:git-Paper-717]
>       at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.9.2.jar:git-Paper-717]
>       at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.9.2.jar:git-Paper-717]
>       at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [patched_1.9.2.jar:git-Paper-717]
>       at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:482) [patched_1.9.2.jar:git-Paper-717]
>       at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:889) [patched_1.9.2.jar:git-Paper-717]
>       at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:55) [patched_1.9.2.jar:git-Paper-717]
>       at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:11) [patched_1.9.2.jar:git-Paper-717]
>       at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.2.jar:git-Paper-717]
>       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
>       at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
>       at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [patched_1.9.2.jar:git-Paper-717]
>       at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:813) [patched_1.9.2.jar:git-Paper-717]
>       at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.2.jar:git-Paper-717]
>       at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:723) [patched_1.9.2.jar:git-Paper-717]
>       at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:622) [patched_1.9.2.jar:git-Paper-717]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
>       at com.mtihc.regionselfservice.v2.plots.PlotListener.onPlayerInteract(PlotListener.java:359) ~[?:?]
>       at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[patched_1.9.2.jar:git-Paper-717]
>       ... 18 more

```

 Thanks :)

**Comment by Hbecher** [comment]
Found it! It was a multiworld issue, the plugin was loaded before your multiworld plugin, so it didn't register the other worlds properly.
Fixed in the latest version.
