### ISSUE TITLE
Breaksign error

### ISSUE THREAD

**Issue by Augustin37** [Hbecher/RegionSelfService#2]
```java
[13:35:48 ERROR]: Could not pass event BlockBreakEvent to RegionSelfService v2.0.2-HB-b7
org.bukkit.event.EventException
>       at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.9.2.jar:git-Paper-717]
>       at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.9.2.jar:git-Paper-717]
>       at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.9.2.jar:git-Paper-717]
>       at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.9.2.jar:git-Paper-717]
>       at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.9.2.jar:git-Paper-717]
>       at net.minecraft.server.v1_9_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:292) [patched_1.9.2.jar:git-Paper-717]
>       at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:124) [patched_1.9.2.jar:git-Paper-717]
>       at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:833) [patched_1.9.2.jar:git-Paper-717]
>       at net.minecraft.server.v1_9_R1.PacketPlayInBlockDig.a(SourceFile:40) [patched_1.9.2.jar:git-Paper-717]
>       at net.minecraft.server.v1_9_R1.PacketPlayInBlockDig.a(SourceFile:10) [patched_1.9.2.jar:git-Paper-717]
>       at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.2.jar:git-Paper-717]
>       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
>       at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
>       at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [patched_1.9.2.jar:git-Paper-717]
>       at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:813) [patched_1.9.2.jar:git-Paper-717]
>       at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.2.jar:git-Paper-717]
>       at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:723) [patched_1.9.2.jar:git-Paper-717]
>       at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:622) [patched_1.9.2.jar:git-Paper-717]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
>       at com.mtihc.regionselfservice.v2.plots.PlotListener.onBlockProtect(PlotListener.java:453) ~[?:?]
>       at com.mtihc.regionselfservice.v2.plots.PlotListener.onBlockProtect(PlotListener.java:406) ~[?:?]
>       at com.mtihc.regionselfservice.v2.plots.PlotListener.onBlockBreak(PlotListener.java:395) ~[?:?]
>       at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[patched_1.9.2.jar:git-Paper-717]
>       ... 18 more
```

**Comment by Hbecher** [comment]
Also a multiworld issue, fixed.
